#### 1. Create Arrays


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
print("Array : ", arr)

Array :  [1 2 3 4 5]


----
#### 2. Array Operations


In [7]:
a = np.array([10,20,30])
b = np.array([1,2,3])
print("a + b = ", a+b)
print("a * b = ",a*b)

a + b =  [11 22 33]
a * b =  [10 40 90]


___
#### 3. Zeros and Ones


In [10]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


----
#### 4. Mean, Max, Min


In [15]:
data = np.array([10,20,30,40])
print("Mean : ",np.mean(data))
print("Max : ",np.max(data))
print("Min : ",np.min(data))

Mean :  25.0
Max :  40
Min :  10
